backend:
  name: github
  repo: cmyk-alt/cilantrowater
  branch: gh-pages
  auth_scope: repo

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
